"""Public domain contracts for AgentActum."""

from agentactum.approvals import ApprovalRequest
from agentactum.compensation import (
    CompensationCoordinator,
    CompensationPlan,
    CompensationResult,
    CompensationSummary,
    CompensationSummaryStatus,
    Compensator,
)
from agentactum.contracts import (
    ActionIntent,
    DuplicateToolRegistrationError,
    RegisteredTool,
    ToolContract,
    ToolHandler,
    ToolRegistry,
    ToolRegistryError,
    ToolSchema,
    UnknownToolError,
)
from agentactum.enums import (
    EffectType,
    PolicyDecisionType,
    RiskLevel,
    TransactionStatus,
)
from agentactum.execution import (
    ApprovalChecker,
    ExecutionResult,
    FailureDetail,
    NoApprovalChecker,
    RuntimeCheck,
    SchemaValidationError,
    SingleActionRuntime,
    StaticApprovalChecker,
)
from agentactum.idempotency import (
    IdempotencyBackend,
    IdempotencyClaim,
    IdempotencyError,
    IdempotencyKeyError,
    IdempotencyOwnershipError,
    IdempotencyRecord,
    IdempotencyRecordStatus,
    InMemoryIdempotencyBackend,
    MissingIdempotencyFieldError,
    create_key,
)
from agentactum.ledger import InMemoryLedger, Ledger, LedgerError, LedgerEvent
from agentactum.outbox import (
    InMemoryOutboxBackend,
    OutboxBackend,
    OutboxError,
    OutboxHandler,
    OutboxOperation,
    OutboxReleaseSummary,
    OutboxStatus,
    UnknownOutboxOperationError,
)
from agentactum.policies import (
    NumericApprovalThresholdPolicy,
    Policy,
    PolicyConstraint,
    PolicyDecision,
    PolicyEngine,
    RequiredPermissionPolicy,
    RiskApprovalPolicy,
    ToolAllowDenyPolicy,
)
from agentactum.transactions import IllegalTransactionTransitionError, Transaction

__version__ = "0.1.0a0"

__all__ = [
    "ActionIntent",
    "ApprovalChecker",
    "ApprovalRequest",
    "CompensationCoordinator",
    "CompensationPlan",
    "CompensationResult",
    "CompensationSummary",
    "CompensationSummaryStatus",
    "Compensator",
    "DuplicateToolRegistrationError",
    "EffectType",
    "ExecutionResult",
    "FailureDetail",
    "IdempotencyBackend",
    "IdempotencyClaim",
    "IdempotencyError",
    "IdempotencyKeyError",
    "IdempotencyOwnershipError",
    "IdempotencyRecord",
    "IdempotencyRecordStatus",
    "IllegalTransactionTransitionError",
    "InMemoryIdempotencyBackend",
    "InMemoryLedger",
    "InMemoryOutboxBackend",
    "Ledger",
    "LedgerError",
    "LedgerEvent",
    "MissingIdempotencyFieldError",
    "NoApprovalChecker",
    "NumericApprovalThresholdPolicy",
    "OutboxBackend",
    "OutboxError",
    "OutboxHandler",
    "OutboxOperation",
    "OutboxReleaseSummary",
    "OutboxStatus",
    "Policy",
    "PolicyConstraint",
    "PolicyDecision",
    "PolicyDecisionType",
    "PolicyEngine",
    "RiskLevel",
    "RegisteredTool",
    "RequiredPermissionPolicy",
    "RiskApprovalPolicy",
    "RuntimeCheck",
    "SchemaValidationError",
    "SingleActionRuntime",
    "StaticApprovalChecker",
    "ToolHandler",
    "ToolContract",
    "ToolAllowDenyPolicy",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolSchema",
    "Transaction",
    "TransactionStatus",
    "UnknownOutboxOperationError",
    "UnknownToolError",
    "__version__",
    "create_key",
]
