"""Public package smoke tests."""

import agentactum


def test_public_package_exports_domain_contracts() -> None:
    """The package exposes version metadata and the intended contract surface."""
    assert agentactum.__version__ == "0.1.0"
    assert set(agentactum.__all__) == {
        "ActionIntent",
        "AgentActum",
        "ApprovalChecker",
        "ApprovalRequest",
        "CompensationCoordinator",
        "CompensationPlan",
        "CompensationResult",
        "CompensationSummary",
        "CompensationSummaryStatus",
        "Compensator",
        "DuplicateToolRegistrationError",
        "EffectType",
        "ExecutionResult",
        "FailureDetail",
        "IdempotencyBackend",
        "IdempotencyClaim",
        "IdempotencyError",
        "IdempotencyKeyError",
        "IdempotencyOwnershipError",
        "IdempotencyRecord",
        "IdempotencyRecordStatus",
        "IllegalTransactionTransitionError",
        "InMemoryIdempotencyBackend",
        "InMemoryLedger",
        "InMemoryOutboxBackend",
        "Ledger",
        "LedgerError",
        "LedgerEvent",
        "MissingIdempotencyFieldError",
        "NoApprovalChecker",
        "NumericApprovalThresholdPolicy",
        "OutboxBackend",
        "OutboxError",
        "OutboxHandler",
        "OutboxOperation",
        "OutboxReleaseSummary",
        "OutboxStatus",
        "Policy",
        "PolicyConstraint",
        "PolicyDecision",
        "PolicyDecisionType",
        "PolicyEngine",
        "RiskLevel",
        "RegisteredTool",
        "RequiredPermissionPolicy",
        "RiskApprovalPolicy",
        "RuntimeCheck",
        "SchemaValidationError",
        "SingleActionRuntime",
        "StaticApprovalChecker",
        "ToolHandler",
        "ToolContract",
        "ToolAllowDenyPolicy",
        "ToolRegistry",
        "ToolRegistryError",
        "ToolSchema",
        "Transaction",
        "TransactionStatus",
        "UnknownOutboxOperationError",
        "UnknownToolError",
        "__version__",
        "create_key",
    }
